-- MySQL Script generated by MySQL Workbench
-- Fri May 29 04:13:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jobs_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jobs_area` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jobs_area` (
  `id_job_area` INT NOT NULL AUTO_INCREMENT,
  `name_job` TEXT NULL,
  PRIMARY KEY (`id_job_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employyes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employyes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employyes` (
  `id_employyes` INT NOT NULL AUTO_INCREMENT,
  `first_name` TEXT NULL,
  `second_name` TEXT NULL,
  `type_identification` ENUM('cedula ciudadania', 'Pasaporte', 'Tarjeta de identidad') NULL,
  `number_identification` INT(12) NULL,
  `id_job_area` INT NOT NULL,
  PRIMARY KEY (`id_employyes`),
  INDEX `fk_employyes_job_area_idx` (`id_job_area` ASC) VISIBLE,
  CONSTRAINT `fk_employyes_job_area`
    FOREIGN KEY (`id_job_area`)
    REFERENCES `mydb`.`jobs_area` (`id_job_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`activities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`activities` (
  `id_activities` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `status` ENUM('realizado', 'pediente') NULL,
  `date_execute` DATETIME NULL,
  `id_employyes` INT NOT NULL,
  PRIMARY KEY (`id_activities`),
  INDEX `fk_activities_employyes1_idx` (`id_employyes` ASC) VISIBLE,
  CONSTRAINT `fk_activities_employyes1`
    FOREIGN KEY (`id_employyes`)
    REFERENCES `mydb`.`employyes` (`id_employyes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
